# Generated by Django 3.2.25 on 2025-01-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
