# Generated by Django 3.2.25 on 2025-01-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250130_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_jobs',
            field=models.ManyToManyField(blank=True, related_name='connected_users', to='app.JobPost'),
        ),
    ]
