# Generated by Django 3.2.25 on 2025-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250131_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
