# Generated by Django 3.2.25 on 2025-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_bio',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
